Fixing some warnings from HPX complaining about use of obsolete types
STEllAR-GROUP/hpx pull request #4990
Opened 2020-09-30 16:53 UTC by hkaiser

There are probably more warnings caused by the recent enabling of the deprecation macros. The changes in this PR make Phylanx compile without those.

2020-09-30 17:48 UTC, msimberg commented
Thanks @hkaiser for fixing these. Any idea why these wouldn't have been triggered earlier? Or did I just not notice before merging?

2020-09-30 18:04 UTC, hkaiser commented
> Thanks @hkaiser for fixing these. Any idea why these wouldn't have been triggered earlier? Or did I just not notice before merging?

I have no idea. Also I'm sure that there are more of those. Especially the use of `execution::is_sequenced_execution_policy` by various algorithm implementations. I have not had the time to do a thorough check for those, however.

2020-09-30 19:09 UTC, msimberg commented
> > Thanks @hkaiser for fixing these. Any idea why these wouldn't have been triggered earlier? Or did I just not notice before merging?
> 
> I have no idea. Also I'm sure that there are more of those. Especially the use of `execution::is_sequenced_execution_policy` by various algorithm implementations. I have not had the time to do a thorough check for those, however.

You (or whoever found these) are not using gcc by any chance? It looks to me like clang doesn't warn about deprecated alias templates: https://godbolt.org/z/o7dYd5. I shall be enabling deprecation warnings on other builders as well (it's only enabled on CircleCI now).

2020-09-30 19:38 UTC, hkaiser commented
> You (or whoever found these) are not using gcc by any chance (edit: I suppose MSVC might warn about them?)? It looks to me like clang doesn't warn about deprecated alias templates: https://godbolt.org/z/o7dYd5. I shall be enabling deprecation warnings on other builders as well (it's only enabled on CircleCI now).

These warnings were produced by MSVC.

2020-10-01 06:57 UTC, msimberg requested changes
Thanks! Looks good to me except for the clang formatting changes reported by CircleCI.

2020-10-01 08:52 UTC, aurianer approved these changes
LGTM thanks!

2020-10-01 13:18 UTC, hkaiser commented
> Thanks! Looks good to me except for the clang formatting changes reported by CircleCI.

Different version of clang-format again *sigh*. I'll fix it.

2020-10-02 17:49 UTC, merged