Replace boost::system::error_code with std::error_code
STEllAR-GROUP/hpx pull request #5009
Opened 2020-10-11 17:49 UTC by K-ballo

2020-10-13 16:13 UTC, K-ballo commented
> > Do we need/want to retain boost serialization (possibly retain but guard by `HPX_SERIALIZATION_WITH_BOOST_TYPES`)?
> 
> I thought we had gotten rid of Boost serialization a long time ago. Anything still in the code base must be a leftover.

I meant serialization of `boost::system::system_error`.

It's unclear to me what the goal behind that support is, but it has been special cased alongside standard exception types, and it isn't guarded by `HPX_SERIALIZATION_WITH_BOOST_TYPES`, so it must have some foundational value. The question is whether that needs to be migrated to `std::system_error`, extended to `std::system_error`, or left as-is.

We are not explicitly throwing `system_error` ourselves (`hpx::exception` extends it, and it has migrated form `boost` to `std`, but that type is also special-cased). These exceptions may be originating from within Boost, likely ASIO (and possibly Filesystem too, before the switch). If that's the scenario the serialization of `boost::system::system_error` caters to then it needs to stay in its current form (ideally eventually wrapped in `hpx::exception` if those originate from core). That would suggest that support ought to have been extended to `std::system_error` already, but I'm not entirely sure.

2020-10-13 23:20 UTC, hkaiser commented
> It's unclear to me what the goal behind that support is, but it has been special cased alongside standard exception types, and it isn't guarded by `HPX_SERIALIZATION_WITH_BOOST_TYPES`, so it must have some foundational value. The question is whether that needs to be migrated to `std::system_error`, extended to `std::system_error`, or left as-is.

The safest way would be to leave it in and guard it with `HPX_SERIALIZATION_WITH_BOOST_TYPES`. As you said, the only reason it might be needed would be Boost.Asio and/or Boost/Filesystem.

2020-10-14 06:58 UTC, msimberg commented
> > It's unclear to me what the goal behind that support is, but it has been special cased alongside standard exception types, and it isn't guarded by `HPX_SERIALIZATION_WITH_BOOST_TYPES`, so it must have some foundational value. The question is whether that needs to be migrated to `std::system_error`, extended to `std::system_error`, or left as-is.
> 
> The safest way would be to leave it in and guard it with `HPX_SERIALIZATION_WITH_BOOST_TYPES`. As you said, the only reason it might be needed would be Boost.Asio and/or Boost/Filesystem.

I suppose the question is if we expect those exceptions to be thrown and then serialized from within HPX or if those are just there for convenience for users encountering boost exceptions. If the former I suppose they should not be guarded, but I'm not sure in what situation that would happen. Would e.g. parcel pool ASIO exceptions from a remote locality end up being serialized to the main locality? Writing that I realize that even if they don't they probably should. If it's only the latter, i.e. for exceptions from user code then guarding with that ifdef sounds appropriate.

2020-10-14 22:52 UTC, K-ballo commented
> Would e.g. parcel pool ASIO exceptions from a remote locality end up being serialized to the main locality?

That is indeed the question.

> Writing that I realize that even if they don't they probably should.

I think those should be transported as HPX exceptions (if they aren't already). The user needs not know to expect ASIO errors.

2020-10-16 15:09 UTC, hkaiser requested changes
I believe this can be removed now as well: https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/HPX_SetupBoost.cmake#L58-L62

2020-10-17 14:00 UTC, K-ballo commented
> I believe this can be removed now as well: https://github.com/STEllAR-GROUP/hpx/blob/master/cmake/HPX_SetupBoost.cmake#L58-L62

We still need to link to Boost.System if ASIO and/or Filesystem internally use it. Filesystem may already be handled at the cmake level, but ASIO doesn't exist as an imported target so it wouldn't pull the usage requirement.

2020-10-17 15:59 UTC, hkaiser approved these changes
LGTM, thanks!

2020-10-23 07:20 UTC, msimberg commented on libs/core/errors/src/exception.cpp
> +        std::system_error const&, std::string const&, std::string const&, long);
I think you'll need to add an explicit template instantiation of `get_exception` above for `std::system_error` as well (or replace the one with `boost::system::system_error`?).

2020-10-23 07:21 UTC, msimberg commented
The build failure with `syscall` is quite mysterious... I'll see if I can figure out what's wrong there.

2020-10-23 09:39 UTC, msimberg commented
@K-ballo the `thread_mapper.cpp` file is missing an `#include <unistd.h>` next to the syscall include (https://github.com/STEllAR-GROUP/hpx/blob/5c06192914e787230f35be7ccd55b496f6f46ffa/libs/full/runtime_local/src/thread_mapper.cpp#L26). I suppose this must have come as a transitive include before these changes. I think you can include it unconditionally (we have a feature check for it) since the syscall include is already guarded by `__linux__` which we know is POSIX.

2020-10-26 19:30 UTC, msimberg commented
Thanks @K-ballo! The remaining test failure is definitely unrelated to these changes.

2020-10-26 19:31 UTC, merged