Lessen constraints on certain algorithm arguments
STEllAR-GROUP/hpx pull request #5027
Opened 2020-10-24 14:03 UTC by hkaiser

- some sequential algorithms (copy, etc.) are fully functional if - when
  used sequentially - the destination is just an output iterator
- fixing is_output_iterator
- flyby: minor formatting changes

2020-10-26 08:12 UTC, msimberg requested changes
Thanks @hkaiser, looks good to me.

2020-10-26 08:12 UTC, msimberg commented on libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/transform_reduce.hpp
> +                        typename hpx::traits::range_traits<Rng>::value_typee,
```suggestion
                        typename hpx::traits::range_traits<Rng>::value_type,
```

2020-10-28 10:24 UTC, aurianer approved these changes
LGTM thanks!

2020-12-12 00:40 UTC, hkaiser commented
@msimberg I think is this is ready to go.

2020-12-14 08:52 UTC, msimberg commented
retest

2020-12-15 08:32 UTC, merged