Replace old init overloads in tests and examples
STEllAR-GROUP/hpx pull request #5050
Opened 2020-11-09 17:21 UTC by aurianer

- Change the  old `hpx::init` overloads to the one using the `struct init_params`
- Add deprecated messages for the old `init` overloads
- Unify the indentation/name of variables for some `init` calls to facilitate the use of scripts

2020-11-09 19:10 UTC, msimberg requested changes
Thank you! Could you please do this for the `start` overloads as well?

2020-11-09 19:10 UTC, msimberg commented on libs/full/init_runtime/include/hpx/hpx_init_impl.hpp
> +            "the new init overloads using the hpx::init_params struct")
```suggestion
    HPX_DEPRECATED_V(1, 6, "The init overload used is deprecated. Please use"
            "the init overloads using the hpx::init_params struct.")
```

2020-11-13 22:53 UTC, aurianer commented
I think this is good to go

2020-11-16 08:57 UTC, msimberg approved these changes
Nice, thanks for doing this!

2020-11-16 08:57 UTC, merged