Remove hipcc guards
STEllAR-GROUP/hpx pull request #5055
Opened 2020-11-17 19:15 UTC by aurianer

Remove the device code guards introduced by #4947

TODO:

- [ ] Remove the guards in the tests and examples

2020-11-17 19:21 UTC, hkaiser reviewed
Could you explain please what has changed such that you were able to remove the guards, please?

2020-11-18 09:42 UTC, msimberg requested changes
Thanks @aurianer. Looking good already, I'd only make a few small changes, but they are minor and not very important.

2020-11-18 09:42 UTC, msimberg commented on src/runtime/agas/detail/hosted_locality_namespace.cpp
> +        return std::vector<std::uint32_t>{1, std::uint32_t(0)};
This can be an empty vector.

2020-11-18 09:44 UTC, msimberg commented
> Could you explain please what has changed such that you were able to remove the guards, please?

@aurianer please expand as necessary. Nothing has changed really. We knew all along that it would be possible to remove them. We just didn't know how difficult it would be and didn't want to block the first iteration of HIP support on resolving that. Turns out that it was easier than we thought, or @aurianer made at least made it look easier ;)

2020-11-18 12:45 UTC, aurianer commented
> Could you explain please what has changed such that you were able to remove the guards, please?

Yes I edited the description of the PR :)

2020-11-18 13:08 UTC, aurianer commented on components/containers/unordered/include/hpx/components/containers/unordered/partition_unordered_map_component.hpp
> +            return ::hpx::make_ready_future(T{});
For the `::hpx` I think it is already used [sometimes](https://gist.github.com/aurianer/3bb281efcdd6499cd9954ef6ae7f943e). Does the compiler search first for symbols in the current namespace or in the no namespace first? I was wondering, as we use `hpx::<something>` symbols quite a lot, if it makes a little difference on the overall codebase, but it's probably nothing so I can totally put `hpx`
Should I also replace the ones that are already on master?

2020-11-18 14:11 UTC, msimberg commented on components/containers/unordered/include/hpx/components/containers/unordered/partition_unordered_map_component.hpp
> +            return ::hpx::make_ready_future(T{});
Hmm, indeed. I suspect we still use `hpx` more often than `::hpx`, so let's stick with it for now. The lookup with `hpx` starts in the current namespace and then successively moves to parent namespaces, which in this case ends up at the top level anyway, so using `::hpx` might be more appropriate eventually. Let's keep the changes here minimal though.

2020-11-19 16:37 UTC, msimberg approved these changes
Thanks @aurianer!

2020-11-19 16:53 UTC, aurianer commented
retest lsu

2020-11-20 07:41 UTC, merged