Slight improvements to min/max/minmax_element algorithms
STEllAR-GROUP/hpx pull request #5372
Opened 2021-06-06 16:52 UTC by hkaiser

2021-06-07 07:47 UTC, msimberg approved these changes

2021-06-07 07:48 UTC, msimberg requested changes

2021-06-07 07:48 UTC, msimberg commented on libs/full/init_runtime_local/src/init_logging.cpp
> +    void disable_logging(logging_destination dest) {}
```suggestion
    void disable_logging(logging_destination) {}
```

2021-06-07 07:49 UTC, msimberg commented on libs/full/init_runtime_local/src/init_logging.cpp
> +    void disable_logging(logging_destination dest) {}
Good to go otherwise. Thanks @hkaiser!

2021-06-08 13:07 UTC, aurianer approved these changes
LGTM thanks!

2021-06-08 16:06 UTC, merged