docs: add links to hpx recepies
STEllAR-GROUP/hpx pull request #5681
Opened 2021-11-26 07:22 UTC by bhumitattarde

Fixes #4016

2021-11-26 20:18 UTC, hkaiser submitted a review, later dismissed
LGTM, thanks!

2021-11-29 10:56 UTC, msimberg requested changes
Thanks @bhumitattarde! Just a minor formatting request, otherwise this looks good.

2021-11-29 10:56 UTC, msimberg commented on docs/sphinx/additional_material.rst
> +* Basic HPX recipes
```suggestion
* Basic |hpx| recipes
```

2021-11-29 13:46 UTC, bhumitattarde commented on docs/sphinx/additional_material.rst
> +* Basic HPX recipes
Done :)

2021-11-29 14:38 UTC, msimberg approved these changes

2021-11-29 14:38 UTC, msimberg commented
bors merge

2021-11-29 14:55 UTC, merged