Add most important CMake options
STEllAR-GROUP/hpx pull request #5687
Opened 2021-12-01 21:59 UTC by dimitraka

Fixes #

Add the agreed most important CMake options in the Manual.

2021-12-02 08:44 UTC, msimberg requested changes
Thanks @dimitraka! A few suggestions in the comments.

2021-12-02 08:44 UTC, msimberg commented on cmake/templates/cmake_variables.rst.in
> +   something other than ``SYSTEM`` requires an external dependency.
```suggestion
   this to ``system``, as custom allocators can hide some memory-related bugs. Note that setting this to 
   something other than ``system`` requires an external dependency.
```

2021-12-02 08:44 UTC, msimberg commented on cmake/templates/cmake_variables.rst.in
> +   only for architectures such as ARM or Power.
```suggestion
   Enable Boost.Context for task context switching. It must be enabled for non-x86 architectures such as ARM and Power.
```

2021-12-02 08:44 UTC, msimberg commented on cmake/templates/cmake_variables.rst.in
> +.. _important_cmake_options:
Would it not be good to put this list somewhere more prominent, like just before this section: https://hpx-docs.stellar-group.org/branches/master/html/manual/building_hpx.html#platform-specific-build-recipes? You could then also include a link from this section to the full list: https://hpx-docs.stellar-group.org/branches/master/html/manual/building_hpx.html#cmake-variables-used-to-configure-hpx.

2021-12-03 15:48 UTC, aurianer submitted a review, later dismissed
LGTM, thanks a lot!

2021-12-03 15:48 UTC, aurianer commented on cmake/templates/cmake_variables.rst.in
> +   important for the performance of HPX applications. When debugging applications, it's useful to set
```suggestion
   important for the performance of |hpx| applications. When debugging applications, it's useful to set 
```
For the specific font?

2021-12-03 15:48 UTC, aurianer commented on cmake/templates/cmake_variables.rst.in
> +   Enable support for CUDA. Use ``CMAKE_CUDA_COMPILER`` to set the CUDA compiler. This is a standard CMake variable,
```suggestion
   Enable support for CUDA. Use ``CMAKE_CUDA_COMPILER`` to set the CUDA compiler. This is a standard |cmake| variable, 
```
?

2021-12-03 15:48 UTC, aurianer commented on cmake/templates/cmake_variables.rst.in
> +   Set the maximum CPU count supported by HPX. The default value is 64, and should be set to a number at least as
```suggestion
   Set the maximum CPU count supported by |hpx|. The default value is 64, and should be set to a number at least as
```

2021-12-09 16:52 UTC, msimberg commented on docs/sphinx/manual/building_hpx.rst
>  CMake variable; e.g. ``HPX_WITH_CXX_STANDARD=20``.
As discussed in the meeting, let's move this to the list of options below. Just adding this comment as a reminder.

2021-12-10 10:08 UTC, msimberg approved these changes
Looks good. Thanks @dimitraka!

2021-12-10 10:08 UTC, msimberg commented
bors merge

2021-12-10 10:38 UTC, merged