Making task_group serializable
STEllAR-GROUP/hpx pull request #5710
Opened 2021-12-14 23:42 UTC by hkaiser

2021-12-15 09:17 UTC, msimberg requested changes
Looks good to me. Just needs fixes for the inspect warnings before merging.

2021-12-15 18:38 UTC, hkaiser commented
This is good to go now.

2021-12-16 09:11 UTC, msimberg commented
bors merge

2021-12-16 09:39 UTC, msimberg approved these changes

2021-12-16 09:40 UTC, msimberg commented
bors merge

2021-12-16 10:04 UTC, merged