New performance counters related to zero-copy chunks.
STEllAR-GROUP/hpx pull request #5879
Opened 2022-05-02 05:07 UTC by JiakunYan

/zchunks/count/{}/{}: total number of zero-copy chunks.
/zchunks/count-max/{}/{}: maximum number of zero-copy chunks per message.
/zchunks/size/{}/{}: total size of zero-copy chunks.
/zchunks/size-max/{}/{}: maximum size of zero-copy chunks.

Still need to update the documentation.

2022-05-02 12:26 UTC, hkaiser commented
Just one question: What are `zchunks`?

2022-05-02 14:36 UTC, JiakunYan commented
> Just one question: What are `zchunks`?

Zero-copy chunks. This is probably not the best name. Do you have any suggestions?

2022-05-02 15:14 UTC, hkaiser commented
> > Just one question: What are `zchunks`?
> 
> Zero-copy chunks. This is probably not the best name. Do you have any suggestions?

What about `/parcelport/count/lci/zero_copy_chunks`?

2022-05-02 15:40 UTC, JiakunYan commented
> > > Just one question: What are `zchunks`?
> > 
> > 
> > Zero-copy chunks. This is probably not the best name. Do you have any suggestions?
> 
> What about `/parcelport/count/lci/zero_copy_chunks`?

Some existing counters:
`/parcels/count/{tcp or mpi or lci}/{sent or received}`: the number of parcels sent/received
`/messages/count/{tcp or mpi or lci}/{sent or received}`: the number of messages sent/received
`/data/time/{tcp or mpi or lci}/{sent or received}`: the total time spent on data transfer on sender/receiver side

I don't think `/parcelport/count/{tcp or mpi or lci}/zero_copy_chunks` follows the same pattern?

2022-05-02 16:26 UTC, hkaiser commented
> > > > Just one question: What are `zchunks`?
> > > 
> > > 
> > > Zero-copy chunks. This is probably not the best name. Do you have any suggestions?
> > 
> > 
> > What about `/parcelport/count/lci/zero_copy_chunks`?
> 
> Some existing counters: `/parcels/count/{tcp or mpi or lci}/{sent or received}`: the number of parcels sent/received `/messages/count/{tcp or mpi or lci}/{sent or received}`: the number of messages sent/received `/data/time/{tcp or mpi or lci}/{sent or received}`: the total time spent on data transfer on sender/receiver side
> 
> I don't think `/parcelport/count/{tcp or mpi or lci}/zero_copy_chunks` follows the same pattern?

I thought it did, actually ;-) So far, performance counter names consisted out of 3 parts: the general topic (`/parcelport`), the 'type' (`/count`), and some additional information explaining what the counter measures (e.g. `/{tcp|mpi|lci|...}/something`). I'm fine with anything however, as long as it roughly follows the existing scheme.

2022-05-03 15:38 UTC, JiakunYan commented
> I thought it did, actually ;-) So far, performance counter names consisted out of 3 parts: the general topic (`/parcelport`), the 'type' (`/count`), and some additional information explaining what the counter measures (e.g. `/{tcp|mpi|lci|...}/something`). I'm fine with anything however, as long as it roughly follows the existing scheme.

Okay, so the counters will be:
/parcelport/count/{tcp|mpi|lci}/zero_copy_chunks/{sent|received}: total number of zero-copy chunks.
/parcelport/count-max/{tcp|mpi|lci}/zero_copy_chunks/{sent|received}: maximum number of zero-copy chunks per message.
/parcelport/size/{tcp|mpi|lci}/zero_copy_chunks/{sent|received}: total size of zero-copy chunks.
/parcelport/size-max/{tcp|mpi|lci}/zero_copy_chunks/{sent|received}: maximum size of zero-copy chunks.

How do you think?

2022-05-03 15:58 UTC, hkaiser commented
> > I thought it did, actually ;-) So far, performance counter names consisted out of 3 parts: the general topic (`/parcelport`), the 'type' (`/count`), and some additional information explaining what the counter measures (e.g. `/{tcp|mpi|lci|...}/something`). I'm fine with anything however, as long as it roughly follows the existing scheme.
> 
> Okay, so the counters will be: /parcelport/count/{tcp|mpi|lci}/zero_copy_chunks/{sent|received}: total number of zero-copy chunks. /parcelport/count-max/{tcp|mpi|lci}/zero_copy_chunks/{sent|received}: maximum number of zero-copy chunks per message. /parcelport/size/{tcp|mpi|lci}/zero_copy_chunks/{sent|received}: total size of zero-copy chunks. /parcelport/size-max/{tcp|mpi|lci}/zero_copy_chunks/{sent|received}: maximum size of zero-copy chunks.
> 
> What do you think?

Sounds good. The only possible issue might be that the last part of the performance counter name (the `/{tcp|mpi|lci}/zero_copy_chunks/{sent|received}`) could be expected to consist of two parts only (not three). Let's try if it works, If you run into issues I'll adapt the parsers responsible for taking apart the names.

2022-05-03 16:22 UTC, JiakunYan commented
> zero_copy_chunks/

It works!
```
python hpxrun.py ./hello_world_distributed -r mpi -l 2 -t 4 -p lci -- --hpx:print-counter /parcelport/count/lci/zero_copy_chunks/sent --hpx:print-counter /parcelport/size/lci/zero_copy_chunks/sent
hello world from OS-thread 3 on locality 1
hello world from OS-thread 0 on locality 1
hello world from OS-thread 2 on locality 0
hello world from OS-thread 3 on locality 0
hello world from OS-thread 1 on locality 0
hello world from OS-thread 0 on locality 0
hello world from OS-thread 2 on locality 1
hello world from OS-thread 1 on locality 1
/parcelport{locality#0/total}/count/lci/zero_copy_chunks/sent,1,0.340167,[s],1
/parcelport{locality#1/total}/count/lci/zero_copy_chunks/sent,1,0.340653,[s],0
/parcelport{locality#0/total}/size/lci/zero_copy_chunks/sent,1,0.340326,[s],164
/parcelport{locality#1/total}/size/lci/zero_copy_chunks/sent,1,0.340934,[s],0

```

2022-05-03 17:23 UTC, hkaiser commented on docs/sphinx/manual/optimizing_hpx_applications.rst
> +       ``<connection_type>`` is one of the following: ``tcp``, ``mpi``
What about `lci` here?

2022-05-03 17:26 UTC, hkaiser requested changes
Could you please go over the documentation one more time and make sure LCI is mentioned wherever needed? 

Otherwise, LGTM, thanks a lot!

2022-05-03 18:23 UTC, JiakunYan commented
> Could you please go over the documentation one more time and make sure LCI is mentioned wherever needed?
> 
> Otherwise, LGTM, thanks a lot!

I think it would better be done in a different PR? It seems to require a lot of changes to the documentation.

2022-05-03 18:32 UTC, hkaiser commented
> > Could you please go over the documentation one more time and make sure LCI is mentioned wherever needed?
> > Otherwise, LGTM, thanks a lot!
> 
> I think it would better be done in a different PR? It seems to require a lot of changes to the documentation.

Sure, let's do that. Let's get this merged. Thanks!

2022-05-03 18:32 UTC, hkaiser submitted a review, later dismissed
LGTM, thanks!

2022-05-03 18:33 UTC, hkaiser commented
bors merge

2022-05-03 18:33 UTC, hkaiser commented
bors cancel

2022-05-03 18:34 UTC, hkaiser commented
There is that compilation problem on the windows builder: https://github.com/STEllAR-GROUP/hpx/runs/6277069011?check_suite_focus=true

2022-05-03 18:36 UTC, hkaiser commented
> There is that compilation problem on the windows builder: https://github.com/STEllAR-GROUP/hpx/runs/6277069011?check_suite_focus=true

Let's not rush this in for the upcoming release. We have all the time we need here.

2022-05-04 19:16 UTC, JiakunYan commented
> There is that compilation problem on the windows builder: https://github.com/STEllAR-GROUP/hpx/runs/6277069011?check_suite_focus=true

Fixed it.

2022-05-25 21:03 UTC, hkaiser approved these changes
LGTM, thanks!

2022-05-25 21:03 UTC, hkaiser commented
bors merge

2022-05-25 22:04 UTC, merged