LCI parcelport uses LCI_putva to transfer messages
STEllAR-GROUP/hpx pull request #5883
Opened 2022-05-04 03:14 UTC by JiakunYan

# Background

LCI_putva: put iovec allocate

- LCI_putva simultaneously transfers an `iovec`, which includes one medium message and multiple long messages. 
- It is a one-sided put operation, which means the target side doesn't need to post a `recv`. Instead, a completion entry will be pushed to a preconfigured LCI completion queue when all messages arrive. 
- Unlike RDMA, the sender side doesn't need to specify a remote registered buffer. LCI runtime will allocate and register the receive buffer.

# Changes on HPX parcelport layer
- No tag management on HPX layer, so no mutex lock.
- Only one "posting send and testing" on the sender side. (It can be further optimized.)
- No "posting receive and testing" on the receive side, so receiver_connection can be removed.

# Progress
### Ongoing
- Implementing a naive version: it uses std::memcpy to copy data from LCI buffers to HPX buffers.

2022-05-25 21:04 UTC, hkaiser commented
@JiakunYan since we have finally finished the release, is there anything you'd still like to do here before merging it?

2022-09-13 20:55 UTC, JiakunYan commented
@hkaiser Do you have any idea why the test "jenkins/lsu/gcc-12-release" failed?

2022-10-03 14:59 UTC, hkaiser requested changes

2022-10-03 14:59 UTC, hkaiser commented on libs/full/parcelport_lci/include/hpx/parcelport_lci/receiver.hpp
> +    struct BufferWrapper
Could you please conform to the HPX naming conventions (not `CamelCase`, but `snake_case`) (see: https://github.com/STEllAR-GROUP/hpx/blob/master/.github/CONTRIBUTING.md#general-info)?

2022-10-03 14:59 UTC, hkaiser commented on libs/full/parcelport_lci/include/hpx/parcelport_lci/receiver.hpp
> +            LCI_request_t request = accept();
Wrapping the `LCI_request_t` into a RAII type that releases it at destruction time would improve exception safety.

2022-10-03 14:59 UTC, hkaiser commented on libs/full/parcelport_lci/include/hpx/parcelport_lci/receiver.hpp
> +            //            // If we don't have a new connection, try to handle one of the
Can this (commented) code be removed?

2022-10-08 23:36 UTC, hkaiser approved these changes
LGTM, thanks!

2022-10-08 23:37 UTC, hkaiser approved these changes

2022-10-08 23:37 UTC, hkaiser commented
bors merge

2022-10-09 00:09 UTC, merged