Fix minor doxygen parsing typo
STEllAR-GROUP/hpx pull request #5916
Opened 2022-06-09 16:38 UTC by gonidelis

Fixes minor typo that might cause hyperlink to break in Doxygen. The warning stems from line #199 and everything below that fails to link to our docs page. Let's merge it as it is a typo anyways and see if it also fixes the linking problem.

I don't think the `\a` clause has to be an one-liner, does it?

2022-06-09 16:50 UTC, gonidelis commented
I summon @bhumitattarde @dimitraka on that.

2022-06-09 17:29 UTC, hkaiser requested changes
A cursory grep for `'   ::type>'` brings up at least one more similar problem in sort.hpp. Could you please fix that as well?

2022-06-11 21:28 UTC, gonidelis commented
> A cursory grep for `' ::type>'` brings up at least one more similar problem in sort.hpp. Could you please fix that as well?

Ok I will track them down all

2022-06-13 00:52 UTC, gonidelis commented
@hkaiser  Let's see if that fixes the problem.

2022-06-13 16:18 UTC, hkaiser approved these changes
LGTM, thanks!

2022-06-13 16:19 UTC, hkaiser commented
bors merge

2022-06-13 16:36 UTC, merged