Fix building on musl.
STEllAR-GROUP/hpx pull request #5947
Opened 2022-07-08 17:18 UTC by listout

These are some patches that make it possible to build hpx on musl.

Signed-off-by: brahmajit das <brahmajit.xyz@gmail.com>

Fixes #5946

## Proposed Changes

- EXEC_PAGESIZE is not defined under musl so including linux/param.h
  where it should be defined. Header linux/param.h does not depend on
  any libc and hence can use included on any linux system.
- execinfo.h is only present on glibc and ulibc, but not on musl so
  before defining HPX_HAVE_EXECINFO it's being checked whether we're on
  a glibc or ulibc system
- RTLD_DI_ORIGIN is not present on musl, hence the alternate
  the solution is implemented if RTLD_DI_ORIGIN is undefined.

## Any background context you want to provide?

hpx was failing to build with musl libc, these patches should fix them without affecting other libc systems

## Checklist

- [ ] I have added a new feature and have added tests to go along with it.
- [ ] I have fixed a bug and have added a regression test.
- [ ] I have added a test using random numbers; I have made sure it uses a seed, and that random numbers generated are valid inputs for the tests.

2022-07-08 18:26 UTC, hkaiser requested changes

2022-07-08 18:26 UTC, hkaiser commented on libs/core/plugin/include/hpx/plugin/detail/dll_dlopen.hpp
> +#if defined(RTLD_DI_ORIGIN)
I think you could join the two `#ifdef` sections above (reorder the lines).

2022-07-08 18:26 UTC, hkaiser commented on libs/core/debugging/src/backtrace.cpp
> +#if (defined(__GLIBC__))
```suggestion
#if defined(__GLIBC__)
```

2022-07-08 19:13 UTC, listout commented
@hkaiser Would like to report that the tests pass when I ran them locally with these patches, both on musl and glibc

2022-07-08 19:24 UTC, hkaiser approved these changes
LGTM, thanks!

2022-07-08 20:32 UTC, listout commented
@hkaiser Looks like some of the tests failed, mainly the tests.unit2. I can there's a backtrace.

2022-07-08 23:09 UTC, hkaiser commented
> @hkaiser Looks like some of the tests failed, mainly the tests.unit2. I can there's a backtrace.

That failure is a known issue and unrelated to your PR. Feel free to ignore it.

2022-07-08 23:09 UTC, hkaiser commented
bors merge

2022-07-08 23:31 UTC, merged

2022-07-09 00:14 UTC, hkaiser commented
@listout Congratulations, your first PR to the HPX repository has just been merged! As a 'thank you' we offer a free STE||AR-Group t-shirt to all of our first-time contributors. If you are interested in receiving one, please get back to me directly so we can set up the delivery.

2022-07-09 03:37 UTC, listout commented
@hkaiser OMG that's so great. How should I contact you, can I send you a mail at `hkaiser at cct dot lsu dot edu`?

2022-07-09 13:52 UTC, hkaiser commented
> @hkaiser OMG that's so great. How should I contact you, can I send you a mail at `hkaiser at cct dot lsu dot edu`?

Yes, that will work.

2022-07-09 13:59 UTC, listout commented
@hkaiser if you receive an email from `brahmajit.xyz at gmail dot com`, that will be.