P2300 enhancements
STEllAR-GROUP/hpx pull request #5990
Opened 2022-08-28 21:46 UTC by SAtacker

Fixes #5838 

## Proposed Changes

  - Adapt `get_completion_signatures` when Sender is a `awaitable`
  - `as_awaitable_t` with `receiver_base`, `sender_awaitable_base`
  - `promise_base`, `operation_base`
  - `connect_awaitable` to adapt connect mentioned in [spec](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2300r5.html#spec-execution.senders.connect) 2.2
  - `with_awaitable_senders`

## Any background context you want to provide?

- Utility `as_awaitable_t` to transform an object into one that is awaitable within a particular coroutine.
- Utility `with_awaitable_senders` used as the base class of a coroutine promise type, makes senders awaitable in that coroutine type

## Checklist

- [ ] I have added a new feature and have added tests to go along with it.

2022-10-12 15:56 UTC, hkaiser requested changes

2022-10-12 15:56 UTC, hkaiser commented on libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp
> +                return tag_invoke(
Or should it even be: 
```suggestion
                return as_awaitable(HPX_FORWARD(Awaitable, await), *this);
```

2022-10-12 15:56 UTC, hkaiser commented on libs/core/execution_base/include/hpx/execution_base/coroutine_utils.hpp
> +#if defined(HPX_HAVE_CXX20_COROUTINES)
```suggestion
#include <hpx/config.hpp>

#if defined(HPX_HAVE_CXX20_COROUTINES)
#include <hpx/assert.hpp>
#include <hpx/datastructures/variant.hpp>
#include <hpx/execution_base/completion_signatures.hpp>
#include <hpx/execution_base/get_env.hpp>
#include <hpx/execution_base/traits/coroutine_traits.hpp>
#include <hpx/functional/detail/tag_fallback_invoke.hpp>
#include <hpx/type_support/meta.hpp>

#include <exception>
#include <system_error>
#include <utility>

```

2022-10-13 12:33 UTC, SAtacker commented on libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp
> +        };
Alright

2022-10-13 12:48 UTC, SAtacker commented on libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp
> +        };
yes, thanks

2022-10-13 13:22 UTC, SAtacker commented on libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp
> +                        return HPX_FORWARD(Value, std::get<1>(result));
Can the `result` hold an `rvalue` type?

2022-10-13 13:33 UTC, SAtacker commented on libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp
> +                // is called.
That's what the standard implementation is doing. Their reasoning convinced me - [ref](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2300r5.html#design-native-coro-unwind)

2022-10-13 13:35 UTC, SAtacker commented on libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp
> +                // is called.
But for HPX, I think we can call something other than std::terminate as we even launch our own main function.

2022-10-13 13:36 UTC, SAtacker commented on libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp
> +        // }
Yes, sorry.

2022-10-14 15:56 UTC, SAtacker commented on libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp
> +                return tag_invoke(
Understood, the latter one seems best suited.

2022-10-14 16:01 UTC, SAtacker commented on libs/core/execution_base/include/hpx/execution_base/coroutine_utils.hpp
> +#if defined(HPX_HAVE_CXX20_COROUTINES)
Yes, thanks

2022-10-18 13:48 UTC, hkaiser commented on libs/core/execution_base/include/hpx/execution_base/completion_signatures.hpp
> +        struct with_awaitable_senders_base
Codacy is complaining about this type having private data members but no constructors. I know that this is a false positive and I have tried to convince it to ignore the issue. Could you please add a 
```
    with_awaitable_senders_base() = default;
```
to this class to silence the warning?

2022-10-26 12:39 UTC, hkaiser submitted a review, later dismissed
LGTM, thanks!

2022-10-27 15:55 UTC, hkaiser commented
bors merge

2022-10-27 16:15 UTC, merged