remove MPI dependency when only using LCI parcelport
STEllAR-GROUP/hpx pull request #6039
Opened 2022-10-09 04:32 UTC by JiakunYan

Previously the LCI parcelport always depends on MPI. This PR removes this dependency.

2022-10-09 15:36 UTC, hkaiser requested changes

2022-10-09 15:36 UTC, hkaiser commented on libs/core/lci_base/src/lci_environment.cpp
> +        return hostname;
Could you please use `asio::ip::host_name();` instead (needs `#include <asio/ip/host_name.hpp>`)?

2022-10-09 22:12 UTC, hkaiser commented on libs/core/lci_base/src/lci_environment.cpp
> +        ;
```suggestion
```

2022-10-09 22:18 UTC, JiakunYan commented
Did a rebase on the current master branch.

2022-10-19 20:50 UTC, hkaiser approved these changes
LGTM, thanks!

2022-10-19 20:52 UTC, hkaiser commented
bors merge

2022-10-19 21:17 UTC, merged