Fix segmented algorithms tests
STEllAR-GROUP/hpx pull request #6221
Opened 2023-04-12 13:40 UTC by Pansysk75

Fixes a group of tests for HPX segmented algorithms, which were occasionally failing due to improper initialization of partitioned_vector. Initialization using partitioned_vector::set_value() is asynchronous and returns a future, but we never waited for it to complete.

2023-04-12 14:01 UTC, hkaiser requested changes
Very nice! Thanks a lot! Could you please fix the clang-format issues? Otherwise LGTM.

2023-04-12 15:02 UTC, hkaiser approved these changes
LGTM, thanks!

2023-04-12 18:47 UTC, Pansysk75 commented
> @Pansysk75 We now could revert the change here [e427e0e](https://github.com/STEllAR-GROUP/hpx/commit/e427e0e50919956b8a095f55401b8a1fdec1a6b7). This was introduced to ignore errors when running the segmented algorithm tests.

I saw some "Timeout" failures on some segmented algorithms on some past CircleCI runs. This fix does not address those failures. For example: [https://app.circleci.com/pipelines/github/STEllAR-GROUP/hpx/14417/workflows/69d7cda3-1ae3-4492-b881-a39d963dd6b5/jobs/340881/tests](url)

I would like to try fixing that as well, but I'm not sure how to approach that issue, or what it's cause might be. The CircleCI error message is not very informative.
Well... there is also a 2Gb debug-log.txt, which is saved as an artifact, but I haven't gotten around to trying to parse that yet.

Let me know if you have any input on that.

2023-04-12 19:19 UTC, Pansysk75 commented
Then there is also` tests.unit.modules.runtime_components.distributed.tcp.migrate_polymorphic_component` failing.
I'll use this PR as an opportunity to look into that as well.

2023-04-12 21:25 UTC, hkaiser commented
> Then there is also` tests.unit.modules.runtime_components.distributed.tcp.migrate_polymorphic_component` failing. I'll use this PR as an opportunity to look into that as well.

I appreciate that. Let's do this on a separate PR, however.

2023-04-12 21:31 UTC, hkaiser commented
> Well... there is also a 2Gb debug-log.txt, which is saved as an artifact, but I haven't gotten around to trying to parse that yet.

Short of reproducing this locally, the log file is all we have.

2023-04-15 13:49 UTC, hkaiser commented
@Pansysk75 While this fixes one issue, it seems that there are more [problems](https://app.circleci.com/pipelines/github/STEllAR-GROUP/hpx/14455/workflows/50cca2fb-0577-41bb-9c4a-8524226a232d/jobs/341638). Should we go ahead with merging this PR anyways?

2023-04-15 14:50 UTC, Pansysk75 commented
> @Pansysk75 While this fixes one issue, it seems that there are more [problems](https://app.circleci.com/pipelines/github/STEllAR-GROUP/hpx/14455/workflows/50cca2fb-0577-41bb-9c4a-8524226a232d/jobs/341638). Should we go ahead with merging this PR anyways?

I agree, let's merge this PR, since I don't have any insight on the "Timeout" issue for the time beign.

2023-04-15 15:27 UTC, merged